blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('',views.blog,name="blog"),
    path('<int:blog_id>',views.detail,name="detail"),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name="home"),
    path('blog/',include('blog.urls'))
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=50)
    date = models.DateField()
    description = models.TextField()
    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=100)
    image = models.ImageField(upload_to='portfolio/images')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render
from . models import Blog
from django.shortcuts import get_object_or_404

# Create your views here.
def blog(request):
    blogs = Blog.objects.order_by('-date')
    return render (request,"blog/blog.html",{'blogs':blogs})

def detail(request,blog_id):
    blog = get_object_or_404(Blog , pk=blog_id)
    return render(request,'blog/detail.html',{'blog':blog})

portfolio/views.py
from django.shortcuts import render
from . models import Project
# Create your views here.
def home(request):
    projects = Project.objects.all()
    return render(request,'portfolio/home.html',{'projects':projects})

blog/templates/blog/blog.html
{% extends 'portfolio/home.html' %}

{% block title %}
    Surya | Blogs
{% endblock %}

{% block content %}
  <div class="jumbotron" id="blog-jumbotron">
    <h1 class="display-4">Blog</h1>
    <p class="lead">Surya has written {{blogs.count}} blog{{blogs.count | pluralize}}</p>
  </div>

  {% for blog in blogs%}
    <div class="container blogs">
      <h2><a href="{% url 'blog:detail' blog.id %}">{{blog.title}}</a></h2><br>
      <p>{{blog.date | date:'M d Y' | upper}}</p>
      <p>{{blog.description | striptags | truncatechars:100}}</p>
    </div>
  {% endfor %}

{% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio/home.html' %}

{% block title %}
    Surya |  {{blog.title}}
{% endblock %}

{% block content %}
<div class="jumbotron" id="blog-jumbotron">
    <h1 class="display-4">{{blog.title}}</h1>
    <p class="lead">{{blog.date}}</p>
</div>

<div class="container" id=" ">
    {{blog.description | safe }}
</div>
   

{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@600&family=Lobster&family=Pacifico&family=Teko:wght@500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'portfolio/style.css' %}">
    <link rel="icon" type="image/png" href="{% static 'portfolio/sun.png' %}">
    <title>{% block title %}Surya{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-light">
        <a class="navbar-brand" href="{% url 'home' %}">
          <img src="{% static 'portfolio/sun.png' %}" height="30" class="inline-block align-items-center" }>
          <span>Surya</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home' %}">Portfolio</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% static 'portfolio/resume-samples.pdf' %}">Resume</a>
            </li>

            <li class="nav-item">
              <a class="nav-link btn btn-warning" href="{% url 'blog:blog' %}">Blog</a>
            </li>
          </ul>
          
        </div>
      </nav>

      {% block content %}{% endblock %}

      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}
{% block title %}
    Surya |  Home
{% endblock %}
{% block content %}
  {% load static %}
  <div class="container">

    <div class="row  align-items-center">

      <div class="col col-sm-12 col-md-6">
        <div class="jumbotron">
          <h1 class="display-4">Hey There!___________</h1>
          <p class="lead">Welcome to my portfolio! Scroll down and have a look at my projects</p>
        </div>
      </div>

      <div class="col col-sm-12 col-md-6" id="image-container">
        <img src="{% static 'portfolio/ethnic_day.jpg' %}">

      </div>

    </div>

  </div>
  
  <div class="container">
    <div class="row">
      <h1 class="m-auto" id="project-heading">Projects</h1>
    </div><hr>
  </div>

  <div id="project-holder">

  {% for project in projects%}
  
  <div class="card" style="width: 18rem;">
    <img class="card-img-top" src="{{ project.image.url }}" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">{{project.title}}</h5>
      <p class="card-text">{{project.description}}</p>
      <a href="{{ project.url }}" target="_blank" class="btn btn-primary">View</a>
    </div>
  </div>

  {% endfor%}

  </div>

{% endblock %}